### ISSUE TITLE
whoismac.c:49:23: error: ‘CURLOPT_TCP_KEEPALIVE’ undeclared (first use in this function); did you mean ‘CURLOPT_COOKIELIST’?

### ISSUE THREAD

**Issue by strasharo** [ZerBea/hcxtools#31]
Tried to build on CentOS 6.9 with gcc 7.2.1 and libcurl-devel-7.19.7-53.el6_9.x86_64:
```
gcc -std=gnu99 -O3 -Wall -Wextra -o whoismac whoismac.c -lcurl
In file included from /usr/include/curl/curl.h:1933:0,
                 from whoismac.c:18:
whoismac.c: In function ‘downloadoui’:
whoismac.c:49:23: error: ‘CURLOPT_TCP_KEEPALIVE’ undeclared (first use in this function); did you mean ‘CURLOPT_COOKIELIST’?
 curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);
                       ^
whoismac.c:49:23: note: each undeclared identifier is reported only once for each function it appears in
make: *** [build] Error 1

```
Commenting out line 49 resolves it.

**Comment by strasharo** [comment]
Thank you.
