### ISSUE TITLE
Issue cross-compiling (OpenWRT)

### ISSUE THREAD

**Issue by adde88** [ZerBea/hcxtools#87]
I've been trying to keep **hcxdumptool** and **hcxtools** up to date for **OpenWRT** with your commits, but something broke with commit bb7623e00210169b56542f789df0ac9126913737 (according to bisect, and manual compilations)
Seems to be related to endianess.
Error message:
```
ccache_cc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto
In file included from hcxpcaptool.c:37:0:
include/hashcatops.c: In function 'writehccaprecord':
include/hashcatops.c:99:6: error: 'hccap_t' has no member named 'eapolsize'
 hccap.eapolsize = byte_swap_16(hccap.eapolsize);
      ^
include/hashcatops.c:99:37: error: 'hccap_t' has no member named 'eapolsize'
 hccap.eapolsize = byte_swap_16(hccap.eapolsize);
                                     ^
In file included from hcxpcaptool.c:38:0:
include/johnops.c: In function 'writejohnrecord':
include/johnops.c:103:6: error: 'hccap_t' has no member named 'eapolsize'
 hccap.eapolsize = byte_swap_16(hccap.eapolsize);
      ^
include/johnops.c:103:37: error: 'hccap_t' has no member named 'eapolsize'
 hccap.eapolsize = byte_swap_16(hccap.eapolsize);
                                     ^
hcxpcaptool.c: At top level:
hcxpcaptool.c:42:0: warning: "BIG_ENDIAN_HOST" redefined [enabled by default]
 #define BIG_ENDIAN_HOST
 ^
In file included from include/ieee80211.c:1:0,
                 from hcxpcaptool.c:30:
include/ieee80211.h:109:0: note: this is the location of the previous definition
 #define BIG_ENDIAN_HOST 1
 ^
make[3]: *** [Makefile:82: hcxpcaptool] Error 1
```

**Comment by ZerBea** [comment]
Please test latest commit:
https://github.com/ZerBea/hcxtools/commit/4ab46ea60dc0de2965d735e0d3529e66882799d4
and close issue, if it fixed the issue.

**Comment by ZerBea** [comment]
I found some more ENDIAN issues and fixed them.
Please test also hcxhash2cap if replaycount is ok in the calculated cap file.

**Comment by adde88** [comment]
It definitely helped a bit, just one error message this time.
Compiling 4ab46ea60dc0de2965d735e0d3529e66882799d4 gives this:
```
ccache_cc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto
In file included from include/ieee80211.c:1:0,
                 from hcxpcaptool.c:30:
include/ieee80211.h:265:20: error: #if with no expression
 #if BIG_ENDIAN_HOST
                    ^
make[3]: *** [Makefile:79: hcxpcaptool] Error 1
```

**Bisect** gives this output:
```
bb7623e00210169b56542f789df0ac9126913737 is the first bad commit
commit bb7623e00210169b56542f789df0ac9126913737
Author: Sebastian Reitenbach <sebastia@l00-bugdead-prods.de>
Date:   Mon Feb 11 22:33:48 2019 +0100

    Fix endianess detection for OpenBSD platforms with compilers
    that don't have __BYTE_ORDER__ defined, i.e. gcc 4.2.

    So for OpenBSD systems, in case __BYTE_ORDER__ is not defined
    include <endian.h> and go from there.

:100644 100644 db34692760860fcd5ba7aac81ea5664b28d9ff08 332471e4b2b8a065cf1299ea23544160d89582ab M      hcxpcaptool.c
:040000 040000 cebf273f53588c1e3dc1a89ad48bb91d1673f64f 91d25803345795455f4061726ff1121ade8f7223 M      include
```

**Comment by adde88** [comment]
That error message was related to "include/ieee80211.h:266"  (#ifdef BIG_ENDIAN_HOST)
Seems to be fixed in later commits. Closing the issue. Thanks :)

**Comment by ZerBea** [comment]
Great. I'm still in the refactoring process to replace all old wlanhcx.... tools with hcx.... versions.

**Comment by adde88** [comment]
Great. I'll be paying attention to all changes. :)
