### ISSUE TITLE
hcxpcaptool.c:3400: error: ‘PATH_MAX’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by strasharo** [ZerBea/hcxtools#30]
Tried to build on CentOS 6.9 with both gcc 4.4.7 and 7.2.1:

gcc 4:
```
gcc -std=gnu99 -O3 -Wall -Wextra -o hcxpcaptool hcxpcaptool.c -lz -lcrypto
In file included from hcxpcaptool.c:32:
include/gzops.c: In function ‘decompressgz’:
include/gzops.c:29: warning: missing initializer
include/gzops.c:29: warning: (near initialization for ‘strm.avail_in’)
hcxpcaptool.c: In function ‘processcapfile’:
hcxpcaptool.c:3400: error: ‘PATH_MAX’ undeclared (first use in this function)
hcxpcaptool.c:3400: error: (Each undeclared identifier is reported only once
hcxpcaptool.c:3400: error: for each function it appears in.)
hcxpcaptool.c:3400: warning: unused variable ‘tmpoutname’
make: *** [build] Error 1
```
gcc 7:
```
hcxpcaptool.c: In function ‘processcapfile’:
hcxpcaptool.c:3400:17: error: ‘PATH_MAX’ undeclared (first use in this function); did you mean ‘AF_MAX’?
 char tmpoutname[PATH_MAX+1];
                 ^~~~~~~~
                 AF_MAX
hcxpcaptool.c:3400:17: note: each undeclared identifier is reported only once for each function it appears in
hcxpcaptool.c:3400:6: warning: unused variable ‘tmpoutname’ [-Wunused-variable]
 char tmpoutname[PATH_MAX+1];
      ^~~~~~~~~~
make: *** [build] Error 1

```

Defining PATH_MAX 255 resolves the issue.

**Comment by RealEnder** [comment]
Don't have CentOS handy, but can you add this in the beginning:
`#include <linux/limits.h>`

**Comment by strasharo** [comment]
Thanks a lot, builds fine with the fix. :+1:

**Comment by puneeth714** [comment]
thanks a lot @RealEnder it worked for me
